require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec
  - rubocop-rspec_rails

AllCops:
  TargetRubyVersion: 2.7.8
  NewCops: enable

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - '**/config/routes.rb'
    - '**/config/**/*.rb'